### ISSUE TITLE
Problems with the hud on Mac

### ISSUE THREAD

**Issue by teolicht** [raysfire/rayshud#88] opened 2018-01-13 20:58 UTC
Hello. First off, I want to make it clear that I didn't understand this: 
`"Replace the current fonts (CERBETICA, CERBETICA_EDITED) with those that have a "-MAC" suffix"` (Sorry, I'm dumb).

I am experiencing multiple problems, I tried installing the hud and using it some time ago and I gave up because of these problems, but I've seen some people using the hud and I love it, but it's really glitchy in some parts for me. Obviously the reason for this is because I'm using a Mac (macOS High Sierra 10.13.2). But as far as I know the hud should work with Mac aswell. 
Here are a few pictures: https://imgur.com/a/mMpO0

Any ideas? I am not using a 4:3 resolution, I'm using 16:10 - 1680x1050. Thank you.

**Comment by teolicht** [comment] 2018-04-14 23:26
@CriticalFlaw Did what you said, unfortunately did not work.

**Comment by CriticalFlaw** [comment] 2018-04-16 12:42
Judging by the screenshots, mac seems to be rendering fonts at a larger scale than what they are supposed to be. Hence why so much text gets cut off as it goes beyond its boundary. Its possible that lowering the font sizes in the client scheme might fix this issue. 

I won't be able to try that until I ix my mac partition, or someone else steps forward and tries it

**Comment by CriticalFlaw** [comment] 2018-08-17 18:25
Duplicate of https://github.com/raysfire/rayshud/issues/11

**Closed by CriticalFlaw** 2018-08-17 18:25 UTC
Labels: bug report
