### ISSUE TITLE
spy bug

### ISSUE THREAD

**Issue by tf2lover** [raysfire/rayshud#84] opened 2017-12-12 15:48 UTC
hello ray (guessing your name is that) i just downloaded rayshud a few minutes ago and i loved then when i went onto a server i discovered what i think is a bug. im a spy main so i went spy then i found out i couldnt see anyones health my teammates and the enemies as spy please fix this because i cant play spy without it
thank you
ps
this is the best hud ive ever seen so fixing this would be greatly appreciated

**Comment by CriticalFlaw** [comment] 2017-12-12 15:50
What resolution are you on and do you have minmode enabled?

**Comment by CriticalFlaw** [comment] 2017-12-20 16:50
I was unable to reproduce the issue on my end. Played Spy (disguised and undisguised) on a Casual server with the latest rayshud version (2017.12.18) in 16:9 1920x1080 resolution with and without minmode. I will need more information in order to fix this.

**Comment by tf2lover** [comment] 2018-01-08 18:07
i wasnt playing with minmode and my res was 1024x768

**Comment by tf2lover** [comment] 2018-01-08 18:10
ill try playing at your res and see if rayshud works properly

**Comment by tf2lover** [comment] 2018-01-08 18:12
ok for some reason i cant play at your res ill try to look into this more myself as well

**Comment by tf2lover** [comment] 2018-01-08 18:16
ok i have tried joining a game but i dont know where to see my teams health it doesnt matter what class i pick i just cant see health (except when a medic heals me)

**Comment by CriticalFlaw** [comment] 2018-03-30 19:39
Possibly fixed in https://github.com/raysfire/rayshud/commit/aeb2dfae93c4078d046b7f798c6dc192d111f559

**Closed by CriticalFlaw** 2018-03-30 19:39 UTC
Labels: bug, un-reproducible

**Comment by CriticalFlaw** [comment] 2018-08-17 18:59
This is caused by the floating health option being enabled. You'll need to disable it to see the health properly, refer to the information [here](https://github.com/raysfire/rayshud#helpsupport).
